name: r2s-original

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/original_op.yml'
#  schedule:
#  - cron: '10 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'aptx17/nanopi-openwrt'
    steps:   
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: . 1_initialization_environment.sh
      - name: Clone Source
        run: |
          git clone https://github.com/project-openwrt/openwrt --depth=1 -b master
      - name: Setup Configuration
        run: |
          cd openwrt
          mv ../original_op.seed .config
          sed -i '/PREEMPT/d' target/linux/rockchip/armv8/config-5.4
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
      - name: Compile
        run: |
          cd openwrt
          rm -f ./feeds.conf.default
          wget https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/feeds.conf.default
          wget -P include/ https://raw.githubusercontent.com/openwrt/openwrt/openwrt-19.07/include/scons.mk
          sed -i 's,SNAPSHOT,,g' include/version.mk
          sed -i 's,snapshots,,g' package/base-files/image-config.in
          sed -i 's/Os/O3/g' include/target.mk
          sed -i 's/O2/O3/g' ./rules.mk
          sed -i 's,-DMULTIT,-Ofast -DMULTIT,g' package/lean/coremark/Makefile
          ./scripts/feeds update -a && ./scripts/feeds install -a
          rm -rf ./feeds/packages/net/miniupnpd
          svn co https://github.com/coolsnowwolf/packages/trunk/net/miniupnpd feeds/packages/net/miniupnpd
          make defconfig
          make download -j8
          make -j$(($(nproc) + 1)) -s
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv openwrt/bin/targets/*/*/*squashfs*img.gz ./artifact/
          cp openwrt/.config ./artifact/
          zip -r artifact.zip ./artifact/
      - name: Upload Firmwares
        uses: actions/upload-artifact@master
        with:
          name: r2s-original-openwrt
          path: ./artifact/
        
