name: r2s minimal 

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/R2s-FriendlyWrt.yml'
#  schedule:
 #   - cron: '10 01 * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'aptx17/nanopi-openwrt'
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /usr/local/share/boost /opt/ghc
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8
          cd friendlywrt/ && git fetch --unshallow
      - name: Update kernel
        run: |
          cd friendlywrt-rk3328
          mv ../scripts/nanopi-r2_linux_defconfig kernel/arch/arm64/configs
      - name: Patch Kernel
        run: |
          . patch_kernel_5.4.sh
      - name: Mods
        run: |
          cd friendlywrt-rk3328
          . ../remove_unused_config.sh
          cat configs/config_rk3328 | grep "TARGET" >> ../base_rk3328.seed
          cat ../base_rk3328.seed > configs/config_rk3328
          sed -i 's,ACCEPT,REJECT,g' device/friendlyelec/rk3328/default-settings/install.sh
          echo '
           CONFIG_KERNEL_BLK_DEV_THROTTLING=y
           CONFIG_KERNEL_BTRFS_FS_POSIX_ACL=y
           CONFIG_KERNEL_KALLSYMS=y
           CONFIG_LUCI_LANG_en=y
           CONFIG_LUCI_LANG_zh_Hans=y
           CONFIG_DEVEL=y
           CONFIG_AUTOREMOVE=y
           CONFIG_TARGET_OPTIONS=y
           CONFIG_TARGET_OPTIMIZATION="-O3 -pipe -mcpu=cortex-a53"
           CONFIG_PACKAGE_kmod-ikconfig=y
           CONFIG_PACKAGE_kmod-cryptodev=y
           CONFIG_PACKAGE_iptables-mod-tproxy=y
           CONFIG_PACKAGE_kmod-ipt-tproxy=y
           CONFIG_PACKAGE_libopenssl-devcrypto=y
           CONFIG_PACKAGE_kmod-crypto-gcm=y
           CONFIG_PACKAGE_dnsmasq-full=y
           CONFIG_PACKAGE_dnsmasq_full_auth=y
           CONFIG_PACKAGE_dnsmasq_full_conntrack=y
           CONFIG_PACKAGE_dnsmasq_full_dhcp=y
           CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
           CONFIG_PACKAGE_dnsmasq_full_dnssec=y
           CONFIG_PACKAGE_dnsmasq_full_ipset=y
           CONFIG_PACKAGE_dnsmasq_full_noid=y
           CONFIG_PACKAGE_dnsmasq_full_tftp=y
           CONFIG_PACKAGE_iptables-mod-fullconenat=y
           CONFIG_PACKAGE_kmod-ipt-nat6=y
           CONFIG_OPENSSL_ENGINE_BUILTIN=y
           CONFIG_OPENSSL_ENGINE_BUILTIN_DEVCRYPTO=y
           CONFIG_PACKAGE_luci-app-firewall=y
           CONFIG_PACKAGE_luci-proto-ppp=y
           CONFIG_PACKAGE_luci-compat=y
           CONFIG_PACKAGE_luci-lib-ip=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_luci-lib-jsonc=y
          CONFIG_PACKAGE_luci-lib-nixio=y
          CONFIG_OPENSSL_WITH_DTLS=y
          CONFIG_OPENSSL_WITH_EC2M=y
          CONFIG_OPENSSL_WITH_NPN=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_uhttpd=y
          CONFIG_PACKAGE_cgi-io=y
          CONFIG_PACKAGE_diffutils=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_kmod-nls-base=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_openssl-util=y
          CONFIG_PACKAGE_openssh-sftp-server=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          # CONFIG_PACKAGE_kmod-leds-gpio is not set
          # CONFIG_PACKAGE_kmod-leds-pca963x is not set
          # CONFIG_PACKAGE_kmod-ledtrig-default-on is not set
          # CONFIG_PACKAGE_kmod-ledtrig-gpio is not set
          # CONFIG_PACKAGE_kmod-ledtrig-heartbeat is not set
          # CONFIG_PACKAGE_kmod-ledtrig-netdev is not set
          # CONFIG_PACKAGE_kmod-ledtrig-oneshot is not set
          # CONFIG_PACKAGE_kmod-ledtrig-timer is not set
          # CONFIG_PACKAGE_kmod-ledtrig-transient is not set
          # CONFIG_PACKAGE_kmod-mppe is not set
          # CONFIG_PACKAGE_fast-classifier-example is not set
          # CONFIG_PACKAGE_luci-app-sfe is not set
          # CONFIG_PACKAGE_kmod-shortcut-fe is not set
          # CONFIG_PACKAGE_kmod-shortcut-fe-cm is not set
          # CONFIG_PACKAGE_luci-app-uhttpd is not set
          # CONFIG_PACKAGE_usb-modeswitch is not set
          # CONFIG_PACKAGE_libusb-1.0 is not set
          # CONFIG_PACKAGE_netdata is not set
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_vsftpd-alt is not set
          # CONFIG_PACKAGE_ddns-scripts is not set
          # CONFIG_PACKAGE_ddns-scripts_aliyun is not set
          # CONFIG_PACKAGE_ddns-scripts_dnspod is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-pppoe-server is not set
          # CONFIG_PACKAGE_luci-app-netdata is not set
          # CONFIG_PACKAGE_luci-app-filetransfer is not set
          # CONFIG_PACKAGE_luci-app-autoreboot is not set
          # CONFIG_PACKAGE_adbyby is not set
          # CONFIG_NGINX_NOPCRE is not set
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          # CONFIG_PACKAGE_shadowsocks-libev-ss-local is not set
          # CONFIG_PACKAGE_shadowsocks-libev-ss-redir is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-alt is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-server is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-local is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2 is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server is not set
          # CONFIG_PACKAGE_luci-app-ssrserver-python is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-ramfree is not set
          # CONFIG_PACKAGE_UnblockNeteaseMusic is not set
          # CONFIG_PACKAGE_UnblockNeteaseMusicGo is not set
          # CONFIG_UnblockNeteaseMusicGo_INCLUDE_GOPROXY is not set
          # CONFIG_UnblockNeteaseMusic_Go is not set
          # CONFIG_UnblockNeteaseMusic_NodeJS is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_watchcat is not set
          # CONFIG_PACKAGE_luci-app-watchcat is not set
          # CONFIG_PACKAGE_vlmcsd is not set
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          # CONFIG_PACKAGE_luci-app-frpc is not set
          # CONFIG_PACKAGE_frpc is not set
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_PACKAGE_v2ray is not set
          # CONFIG_PACKAGE_v2ray-plugin is not set
          # CONFIG_v2ray-plugin_INCLUDE_GOPROXY is not set
          # CONFIG_PACKAGE_python is not set
          # CONFIG_PACKAGE_python-base is not set
          # CONFIG_PACKAGE_iw is not set
          # CONFIG_PACKAGE_iwinfo is not set
          # CONFIG_PACKAGE_hostapd is not set
          # CONFIG_PACKAGE_hostapd-basic is not set
          # CONFIG_PACKAGE_hostapd-utils is not set
          # CONFIG_PACKAGE_wpad is not set
          # CONFIG_PACKAGE_wpad-mini is not set
          # CONFIG_PACKAGE_wpa-supplicant is not set
          # CONFIG_DRIVER_11N_SUPPORT is not set
          # CONFIG_DRIVER_11AC_SUPPORT is not set
          # CONFIG_DRIVER_11W_SUPPORT is not set
          # CONFIG_PACKAGE_kmod-brcmfmac is not set
          # CONFIG_PACKAGE_kmod-cfg80211 is not set
          # CONFIG_PACKAGE_kmod-mmc is not set
          # CONFIG_PACKAGE_wireless-regdb is not set
          # CONFIG_PACKAGE_libiwinfo-lua is not set
          # CONFIG_PACKAGE_libiwinfo is not set
          # CONFIG_PACKAGE_iptables-mod-conntrack-extra is not set
          # CONFIG_PACKAGE_iptables-mod-ipopt is not set
          # CONFIG_PACKAGE_kmod-crypto-authenc is not set
          # CONFIG_PACKAGE_kmod-ifb is not set
          # CONFIG_PACKAGE_kmod-ipt-conntrack-extra is not set
          # CONFIG_PACKAGE_kmod-ipt-ipopt is not set
          # CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
          # CONFIG_PACKAGE_kmod-sched-cake is not set
          # CONFIG_PACKAGE_kmod-sched-core is not set
          # CONFIG_PACKAGE_libnatpmp is not set
          # CONFIG_PACKAGE_kmod-tun is not set
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-sqm is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Socks is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          # CONFIG_PACKAGE_nlbwmon is not set
          # CONFIG_PACKAGE_sqm-scripts is not set
          # CONFIG_PACKAGE_tc is not set
          # CONFIG_PACKAGE_zerotier is not set
          # CONFIG_TARGET_ROOTFS_TARGZ is not set
          # CONFIG_POSTFIX_TLS is not set
          # CONFIG_POSTFIX_SASL is not set
          # CONFIG_POSTFIX_LDAP is not set
          # CONFIG_POSTFIX_DB is not set
          # CONFIG_POSTFIX_CDB is not set
          # CONFIG_POSTFIX_SQLITE is not set
          # CONFIG_POSTFIX_PGSQL is not set
          # CONFIG_POSTFIX_PCRE is not set
          # CONFIG_POSTFIX_EAI is not set
          # CONFIG_PACKAGE_ssmtp is not set          
          ' >> configs/config_rk3328
          cd friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/coolsnowwolf/openwrt && git fetch upstream
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto upstream/lede-17.01 -X theirs
          rm target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch
          sed -i '/ipv6/,+3d' package/base-files/files/root/setup.sh
          git checkout upstream/master -- feeds.conf.default
          sed -i '5s/#src-git/src-git/g' feeds.conf.default
          cd package/lean/
          rm -rf luci-theme-argon
          git clone https://github.com/jerrykuku/luci-theme-argon.git
          cd ../../
          #git apply ../../enable_autocore.diff
          #git apply ../../fix_cpufreq.diff
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase="/luci-static/argon"' package/lean/default-settings/files/zzz-default-settings
          sed -i 's/option fullcone\t1/option fullcone\t0/' package/network/config/firewall/files/firewall.config
          sed -i '/8.8.8.8/d' package/base-files/files/root/setup.sh
          sed -i 's/Os/O3/g' include/target.mk
          sed -i 's/O2/O3/g' ./rules.mk
          sed -i 's,-DMULTIT,-Ofast -DMULTIT,g' package/lean/coremark/Makefile
          mv ../../scripts/checkwan.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/checkwan.sh &' package/base-files/files/etc/rc.local
          mv ../../scripts/check_wan4.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/check_wan4.sh &' package/base-files/files/etc/rc.local
          echo -e '\nDYC Build\n' >> package/base-files/files/etc/banner
      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
      - name: Fix 1001
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -P ${lodev} friendlywrt-rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount ${lodev}p1 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d ${lodev}
      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
          zip -r artifact.zip ./artifact/
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: NanoPi-R2S-FriendlyWrt-kernel-5.4.40
          path: ./artifact/
