name: r2s minimal

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/R2s-FriendlyWrt.yml'
#  schedule:
 #   - cron: '00 01 * * *'
   
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.repository == 'aptx17/nanopi-openwrt'     
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update -y
          sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo -E apt-get autoremove -y --purge
          sudo -E apt-get clean -y
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8
          cd friendlywrt/ && git fetch --unshallow
      - name: Update kernel
        run: |
          cd friendlywrt-rk3328
          cp -f ../scripts/nanopi-r2_linux_defconfig kernel/arch/arm64/configs
          cp -f ../scripts/back/rk3328.dtsi kernel/arch/arm64/boot/dts/rockchip
          cp -f ../scripts/back/host.c kernel/drivers/usb/dwc3
      - name: Patch Kernel
        run: |
          . patch_kernel_5.4.sh
      - name: Mods
        run: |
          cd friendlywrt-rk3328
          . ../remove_unused_config.sh
          cat configs/config_rk3328 | grep "TARGET" >> ../base_rk3328.seed
          cat ../base_rk3328.seed > configs/config_rk3328
          sed -i 's,ACCEPT,REJECT,g' device/friendlyelec/rk3328/default-settings/install.sh
          cd friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/coolsnowwolf/openwrt && git fetch upstream
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto upstream/lede-17.01 -X theirs
          rm target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-add-support-for-rgmii-internal-delay-mo.patch target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch target/linux/generic/hack-4.14/999-net-patch-linux-kernel-to-support-shortcut-fe.patch
          rm target/linux/rockchip-rk3328/base-files/etc/init.d/fa-rk3328-pwmfan target/linux/rockchip-rk3328/base-files/etc/rc.d/S96fa-rk3328-pwmfan target/linux/rockchip-rk3328/base-files/etc/modules.d/10-bcmdhd target/linux/rockchip-rk3328/base-files/etc/modules.d/10-rtl8812au target/linux/rockchip-rk3328/base-files/etc/modules.d/10-rtl8821cu target/linux/rockchip-rk3328/base-files/etc/modules.d/10-rtl8822bu
          rm package/base-files/files/etc/init.d/fa-wifiap package/base-files/files/etc/rc.d/S11fa-wifiap package/base-files/files/etc/hotplug.d/usb/31-usb_wifi package/base-files/files/etc/hotplug.d/usb/30-usb_wifi_huawei package/base-files/files/etc/hotplug.d/ieee80211/09-wireless-bcm4356 package/base-files/files/etc/modules.d/90-8189es package/base-files/files/etc/modules.d/90-8821cu package/base-files/files/etc/modules.d/xradio_wlan package/base-files/files/usr/bin/lcd2usb_echo
          git checkout upstream/master -- feeds.conf.default && sed -i -E 's/#(src-git.+)(helloworld.+)/\1\2/' feeds.conf.default
          ./scripts/feeds update -a && ./scripts/feeds install -a
          wget -O- https://raw.githubusercontent.com/aptx17/nanopi-openwrt/master/scripts/fullconenat-switch.patch | patch -p1
          wget -O- https://raw.githubusercontent.com/aptx17/nanopi-openwrt/master/scripts/zzz-default-settings.patch | patch -p1
          rm -rf package/network/services/dnsmasq package/network/ipv6 package/network/config/netifd package/network/services/odhcpd package/network/utils/iptables package/network/utils/iproute2 package/network/utils/ethtool 
          svn co https://github.com/coolsnowwolf/lede/trunk/package/network/services/dnsmasq package/network/services/dnsmasq
          svn co https://github.com/openwrt/openwrt/branches/openwrt-21.02/package/network/ipv6 package/network/ipv6
          svn co https://github.com/openwrt/openwrt/branches/openwrt-21.02/package/network/config/netifd package/network/config/netifd
          svn co https://github.com/coolsnowwolf/lede/trunk/package/network/services/odhcpd package/network/services/odhcpd
          svn co https://github.com/openwrt/openwrt/branches/openwrt-21.02/package/network/utils/iptables package/network/utils/iptables
          svn co https://github.com/openwrt/openwrt/branches/openwrt-21.02/package/network/utils/iproute2 package/network/utils/iproute2
          svn co https://github.com/openwrt/openwrt/branches/openwrt-21.02/package/network/utils/ethtool package/network/utils/ethtool
          cd package/lean/
          rm -rf coremark
          svn co https://github.com/immortalwrt/packages/trunk/utils/coremark ./coremark
          rm -rf autocore
          svn co https://github.com/immortalwrt/immortalwrt/branches/master/package/lean/autocore ./autocore
          sed -i 's/TARGET_rockchip/TARGET_rockchip_rk3328/g' ./autocore/Makefile
          sed -i 's,boardinfo.model + cpubench.cpubench,"FriendlyElec NanoPi R2S®",g' ./autocore/files/arm/rpcd_10_system.js
          sed -i 's,cpuinfo.cpuinfo,"RK3328 SoC ARMv8-A Cortex-A53 Quad-Core @ 1.5GHz",g' ./autocore/files/arm/rpcd_10_system.js
          sed -i "/Firmware Version/i\\\t\t\t_('CPU Info'),         cpuinfo.cpuinfo + cpubench.cpubench," ./autocore/files/arm/rpcd_10_system.js
          sed -i "/_('CPU usage (%)'),    cpuusage.cpuusage/d" ./autocore/files/arm/rpcd_10_system.js
          sed -i 's/echo -n "${cpu_arch} x ${cpu_cores} (${big_cpu_freq}${cpu_freq}, ${cpu_temp})"/echo -n "${cpu_freq} | ${cpu_temp} | "/g' ./autocore/files/arm/cpuinfo
          cd ../../
          cp -f ../../scripts/fa-rk3328-misc target/linux/rockchip-rk3328/base-files/etc/init.d/fa-rk3328-misc
          wget -P target/linux/rockchip-rk3328/base-files/etc/rc.d/ https://raw.githubusercontent.com/friendlyarm/friendlywrt/0ef1aa8c5ac25207a461628f6e56da3f5633ceb1/target/linux/rockchip-rk3328/base-files/etc/rc.d/S96fa-rk3328-misc
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase="/luci-static/bootstrap"' package/lean/default-settings/files/zzz-default-settings
          sed -i '\|^/usr/bin/lcd2usb_echo &|d' package/base-files/files/etc/rc.local
          sed -i 's/Os/O3/g' include/target.mk
          sed -i 's/O2/O3/g' ./rules.mk
      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          rm scripts/sd-fuse/prebuilt/firmware/system.tgz
          cp -f ../scripts/lib.tgz scripts/sd-fuse/prebuilt/firmware
          cp -f ../scripts/setup_boot_and_rootfs.sh scripts/sd-fuse/tools
          cp -f ../scripts/build-kernel.sh scripts/sd-fuse
          ./build.sh nanopi_r2s.mk
      - name: Fix 1001
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -P ${lodev} friendlywrt-rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount ${lodev}p1 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d ${lodev}
      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv friendlywrt-rk3328/out/*img.gz* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
          zip -r artifact.zip ./artifact/
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: NanoPi-R2S-FriendlyWrt-kernel-5.4.75
          path: ./artifact/
